### ISSUE TITLE
Unable to edit previously opened issue

### ISSUE THREAD

**Issue by stelewis** [marekjm/issue#12]
Hi Marek, thanks for the effort you've put into building this tool - it's excellent! One question I wanted to ask is how one might edit a previously created issue? I imagine this might not be possible given the shasum identifier. If that is the case, feel free to let me know. Thanks

**Comment by marekjm** [comment]
Hi!

I usually add a comment to the issue when I want to add/amend some details. If you wanted to edit the initial issue, you can always open the issue object (all the objects are just plain JSON files) in `$EDITOR` and edit it manually. It is not really an ergonomic solution though...

How to find the issue object? Assume the ID is `deadbeef`. Then the initial object is in:
```
.issue/objects/issues/de/deadbeef/diff/XYZ.json
```
where `XYZ.json` is the oldest file. The diffs are used to create a single object during indexing, so it is best not edit the cached file - you would lose your edit.

**Comment by marekjm** [comment]
I can see the utility of something like `issue edit deadbeef` though.

**Comment by stelewis** [comment]
Thanks for the reply! Makes sense, I'll use editing the JSON, I acknowledge that `issue edit deadbeef` is probably a less common need than just adding a comment as you noted!

**Comment by marekjm** [comment]
Or see commit 1e7cb367f0e3e64bb892b22288b57b95523ecac8. You can now run
```
]$ issue open -E <existing-id>
```
to edit the opening message of an issue. It won't modify the initial diff in-place, but will create a new one; so not only you do not have to edit JSON manually, you will also retain full history. This is much more elegant than the "solution" of "just mess it up with `$EDITOR`".

**Comment by stelewis** [comment]
Amazing! That's perfect. Thanks so much Marek :)
