### ISSUE TITLE
How to checkout comments added to the issue

### ISSUE THREAD

**Issue by intuitiv** [marekjm/issue#9]

**Comment by marekjm** [comment]
`issue show -c deadbeef` (to see full help for the `show` command use `issue help -vc show`)

The `-c` option will display attached comments, if there are any. Comment threads can get quite lengthy so they are hidden by default. There is no configuration option currently that can be used to affect this default behaviour.

If this answer fixes your problem please close the issue. Thanks for reaching out and happy hacking!

**Comment by fredbsc** [comment]
I'm afraid, there is no -c option on show (version 0.4.7). Any ideas? Thx a lot - great tool!!

**Comment by marekjm** [comment]
No `-c` option for the `show` command? Weird... It is defined in the UI file [here](https://github.com/marekjm/issue/blob/devel/ui.json#L551) and handled [here](https://github.com/marekjm/issue/blob/devel/issue.py#L1651).

Try to pull from `devel` branch, run `make install` and see if you get this output:

```
$ issue --version --verbose
issue version 0.4.8 (c1e37719fd3009f1620561d4195b5a5dec554f5f)
```

I just bumped the version to make sure we all are running the same code.

PS. Glad you like the tool. I do too!
